FROM python:3.12-slim
WORKDIR /app
COPY services/celery-connector/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY services/celery-connector/main.py .
CMD ["python", "main.py"]
