"""initial_schema

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployments",
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("commit_hash", sa.String(length=80), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("environment", sa.String(length=30), nullable=False),
        sa.Column("changed_files", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deployments_created_at"), "deployments", ["created_at"], unique=False)
    op.create_index(op.f("ix_deployments_scope_id"), "deployments", ["scope_id"], unique=False)
    op.create_table(
        "experiments",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("configurations", sa.JSON(), nullable=False),
        sa.Column("faults", sa.JSON(), nullable=False),
        sa.Column("trials", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("history_snapshot", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_experiments_created_at"), "experiments", ["created_at"], unique=False)
    op.create_table(
        "metric_samples",
        sa.Column("values", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_metric_samples_created_at"), "metric_samples", ["created_at"], unique=False)
    op.create_table(
        "runtime_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "stream_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("topic", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=60), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_executions",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("queue", sa.String(length=60), nullable=False),
        sa.Column("worker", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("idempotent", sa.Boolean(), nullable=False),
        sa.Column("quarantined", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("delivery_count", sa.Integer(), nullable=False),
        sa.Column("exception", sa.Text(), nullable=True),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("trace_context", sa.JSON(), nullable=False),
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("dispatch_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatch_attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_task_executions_correlation_id"), "task_executions", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_task_executions_created_at"), "task_executions", ["created_at"], unique=False)
    op.create_index(op.f("ix_task_executions_queue"), "task_executions", ["queue"], unique=False)
    op.create_index(op.f("ix_task_executions_scope_id"), "task_executions", ["scope_id"], unique=False)
    op.create_index(op.f("ix_task_executions_status"), "task_executions", ["status"], unique=False)
    op.create_index(op.f("ix_task_executions_trace_id"), "task_executions", ["trace_id"], unique=False)
    op.create_index(op.f("ix_task_executions_worker"), "task_executions", ["worker"], unique=False)
    op.create_table(
        "workers",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("active", sa.JSON(), nullable=False),
        sa.Column("reserved", sa.JSON(), nullable=False),
        sa.Column("scheduled", sa.JSON(), nullable=False),
        sa.Column("queues", sa.JSON(), nullable=False),
        sa.Column("completed", sa.Integer(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_workers_created_at"), "workers", ["created_at"], unique=False)
    op.create_table(
        "incidents",
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("component", sa.String(length=80), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("worker", sa.String(length=100), nullable=True),
        sa.Column("queue", sa.String(length=60), nullable=True),
        sa.Column("symptoms", sa.JSON(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("investigation_requested", sa.Boolean(), nullable=False),
        sa.Column("requested_configuration", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_incident_correlation", "incidents", ["fingerprint", "scope_id", "last_seen_at"], unique=False
    )
    op.create_index(op.f("ix_incidents_created_at"), "incidents", ["created_at"], unique=False)
    op.create_index(op.f("ix_incidents_fingerprint"), "incidents", ["fingerprint"], unique=False)
    op.create_index(op.f("ix_incidents_scope_id"), "incidents", ["scope_id"], unique=False)
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_index(op.f("ix_incidents_task_id"), "incidents", ["task_id"], unique=False)
    op.create_table(
        "processed_records",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_processed_records_created_at"), "processed_records", ["created_at"], unique=False
    )
    op.create_table(
        "task_logs",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_logs_created_at"), "task_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_task_logs_task_id"), "task_logs", ["task_id"], unique=False)
    op.create_table(
        "detection_receipts",
        sa.Column("log_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["log_id"],
            ["task_logs.id"],
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_table(
        "incident_events",
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incident_events_created_at"), "incident_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_incident_events_incident_id"), "incident_events", ["incident_id"], unique=False)
    op.create_table(
        "investigations",
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("configuration", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("prompt_version", sa.String(length=30), nullable=False),
        sa.Column("workflow_version", sa.String(length=30), nullable=False),
        sa.Column("retrieval_snapshot", sa.JSON(), nullable=False),
        sa.Column("history_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_investigations_created_at"), "investigations", ["created_at"], unique=False)
    op.create_index(op.f("ix_investigations_incident_id"), "investigations", ["incident_id"], unique=False)
    op.create_table(
        "diagnoses",
        sa.Column("investigation_id", sa.String(length=36), nullable=False),
        sa.Column("root_cause", sa.String(length=60), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("affected_component", sa.String(length=80), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("supporting_evidence", sa.JSON(), nullable=False),
        sa.Column("contradicting_evidence", sa.JSON(), nullable=False),
        sa.Column("alternative_hypotheses", sa.JSON(), nullable=False),
        sa.Column("recommended_action", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_diagnoses_created_at"), "diagnoses", ["created_at"], unique=False)
    op.create_index(op.f("ix_diagnoses_investigation_id"), "diagnoses", ["investigation_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("investigation_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("component", sa.String(length=80), nullable=False),
        sa.Column("retrieval_method", sa.String(length=80), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_created_at"), "evidence", ["created_at"], unique=False)
    op.create_index(op.f("ix_evidence_incident_id"), "evidence", ["incident_id"], unique=False)
    op.create_index(op.f("ix_evidence_investigation_id"), "evidence", ["investigation_id"], unique=False)
    op.create_table(
        "experiment_runs",
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("configuration", sa.String(length=30), nullable=False),
        sa.Column("fault_type", sa.String(length=60), nullable=False),
        sa.Column("trial", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("ground_truth", sa.String(length=60), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("metadata_snapshot", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column("investigation_id", sa.String(length=36), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("experiment_id", "configuration", "fault_type", "trial"),
    )
    op.create_index(op.f("ix_experiment_runs_created_at"), "experiment_runs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_experiment_runs_experiment_id"), "experiment_runs", ["experiment_id"], unique=False
    )
    op.create_table(
        "investigation_steps",
        sa.Column("investigation_id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("tool", sa.String(length=100), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("observation", sa.JSON(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("investigation_id", "number"),
    )
    op.create_index(
        op.f("ix_investigation_steps_created_at"), "investigation_steps", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_investigation_steps_investigation_id"),
        "investigation_steps",
        ["investigation_id"],
        unique=False,
    )
    op.create_table(
        "llm_usage",
        sa.Column("investigation_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.Column("latency_seconds", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_usage_created_at"), "llm_usage", ["created_at"], unique=False)
    op.create_index(op.f("ix_llm_usage_investigation_id"), "llm_usage", ["investigation_id"], unique=False)
    op.create_table(
        "diagnosis_evidence",
        sa.Column("diagnosis_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["diagnosis_id"],
            ["diagnoses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("diagnosis_id", "evidence_id", "role"),
    )
    op.create_index(
        op.f("ix_diagnosis_evidence_created_at"), "diagnosis_evidence", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_diagnosis_evidence_diagnosis_id"), "diagnosis_evidence", ["diagnosis_id"], unique=False
    )
    op.create_table(
        "experiment_metrics",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["experiment_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_index(
        op.f("ix_experiment_metrics_created_at"), "experiment_metrics", ["created_at"], unique=False
    )
    op.create_table(
        "fault_injections",
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("fault_type", sa.String(length=60), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("ground_truth", sa.String(length=60), nullable=False),
        sa.Column("component", sa.String(length=60), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("injected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["experiment_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_id"),
    )
    op.create_index(op.f("ix_fault_injections_created_at"), "fault_injections", ["created_at"], unique=False)
    op.create_index(op.f("ix_fault_injections_run_id"), "fault_injections", ["run_id"], unique=False)
    op.create_table(
        "historical_incidents",
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("diagnosis_id", sa.String(length=36), nullable=False),
        sa.Column("document", sa.Text(), nullable=False),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("embedding_model", sa.String(length=150), nullable=False),
        sa.Column("indexed", sa.Boolean(), nullable=False),
        sa.Column("index_error", sa.String(length=200), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["diagnosis_id"],
            ["diagnoses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("incident_id"),
    )
    op.create_index(
        op.f("ix_historical_incidents_created_at"), "historical_incidents", ["created_at"], unique=False
    )
    op.create_table(
        "verifications",
        sa.Column("diagnosis_id", sa.String(length=36), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verification_score", sa.Float(), nullable=False),
        sa.Column("supporting_checks", sa.JSON(), nullable=False),
        sa.Column("contradictions", sa.JSON(), nullable=False),
        sa.Column("missing_evidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["diagnosis_id"],
            ["diagnoses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_verifications_created_at"), "verifications", ["created_at"], unique=False)
    op.create_index(op.f("ix_verifications_diagnosis_id"), "verifications", ["diagnosis_id"], unique=False)
    op.create_table(
        "remediations",
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("diagnosis_id", sa.String(length=36), nullable=False),
        sa.Column("verification_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("risk", sa.String(length=20), nullable=False),
        sa.Column("policy_decision", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("requested", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["diagnosis_id"],
            ["diagnoses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verification_id"],
            ["verifications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("diagnosis_id"),
    )
    op.create_index(op.f("ix_remediations_created_at"), "remediations", ["created_at"], unique=False)
    op.create_index(op.f("ix_remediations_incident_id"), "remediations", ["incident_id"], unique=False)
    op.create_table(
        "approval_requests",
        sa.Column("remediation_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("decided_by", sa.String(length=100), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["remediation_id"],
            ["remediations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("remediation_id"),
    )
    op.create_index(
        op.f("ix_approval_requests_created_at"), "approval_requests", ["created_at"], unique=False
    )
    op.create_table(
        "remediation_executions",
        sa.Column("remediation_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("automatic", sa.Boolean(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observe_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("post_result", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["remediation_id"],
            ["remediations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("remediation_id"),
    )
    op.create_index(
        op.f("ix_remediation_executions_created_at"), "remediation_executions", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_remediation_executions_created_at"), table_name="remediation_executions")
    op.drop_table("remediation_executions")
    op.drop_index(op.f("ix_approval_requests_created_at"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index(op.f("ix_remediations_incident_id"), table_name="remediations")
    op.drop_index(op.f("ix_remediations_created_at"), table_name="remediations")
    op.drop_table("remediations")
    op.drop_index(op.f("ix_verifications_diagnosis_id"), table_name="verifications")
    op.drop_index(op.f("ix_verifications_created_at"), table_name="verifications")
    op.drop_table("verifications")
    op.drop_index(op.f("ix_historical_incidents_created_at"), table_name="historical_incidents")
    op.drop_table("historical_incidents")
    op.drop_index(op.f("ix_fault_injections_run_id"), table_name="fault_injections")
    op.drop_index(op.f("ix_fault_injections_created_at"), table_name="fault_injections")
    op.drop_table("fault_injections")
    op.drop_index(op.f("ix_experiment_metrics_created_at"), table_name="experiment_metrics")
    op.drop_table("experiment_metrics")
    op.drop_index(op.f("ix_diagnosis_evidence_diagnosis_id"), table_name="diagnosis_evidence")
    op.drop_index(op.f("ix_diagnosis_evidence_created_at"), table_name="diagnosis_evidence")
    op.drop_table("diagnosis_evidence")
    op.drop_index(op.f("ix_llm_usage_investigation_id"), table_name="llm_usage")
    op.drop_index(op.f("ix_llm_usage_created_at"), table_name="llm_usage")
    op.drop_table("llm_usage")
    op.drop_index(op.f("ix_investigation_steps_investigation_id"), table_name="investigation_steps")
    op.drop_index(op.f("ix_investigation_steps_created_at"), table_name="investigation_steps")
    op.drop_table("investigation_steps")
    op.drop_index(op.f("ix_experiment_runs_experiment_id"), table_name="experiment_runs")
    op.drop_index(op.f("ix_experiment_runs_created_at"), table_name="experiment_runs")
    op.drop_table("experiment_runs")
    op.drop_index(op.f("ix_evidence_investigation_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_incident_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_created_at"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_diagnoses_investigation_id"), table_name="diagnoses")
    op.drop_index(op.f("ix_diagnoses_created_at"), table_name="diagnoses")
    op.drop_table("diagnoses")
    op.drop_index(op.f("ix_investigations_incident_id"), table_name="investigations")
    op.drop_index(op.f("ix_investigations_created_at"), table_name="investigations")
    op.drop_table("investigations")
    op.drop_index(op.f("ix_incident_events_incident_id"), table_name="incident_events")
    op.drop_index(op.f("ix_incident_events_created_at"), table_name="incident_events")
    op.drop_table("incident_events")
    op.drop_table("detection_receipts")
    op.drop_index(op.f("ix_task_logs_task_id"), table_name="task_logs")
    op.drop_index(op.f("ix_task_logs_created_at"), table_name="task_logs")
    op.drop_table("task_logs")
    op.drop_index(op.f("ix_processed_records_created_at"), table_name="processed_records")
    op.drop_table("processed_records")
    op.drop_index(op.f("ix_incidents_task_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_scope_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_fingerprint"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_created_at"), table_name="incidents")
    op.drop_index("ix_incident_correlation", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_workers_created_at"), table_name="workers")
    op.drop_table("workers")
    op.drop_index(op.f("ix_task_executions_worker"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_trace_id"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_status"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_scope_id"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_queue"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_created_at"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_correlation_id"), table_name="task_executions")
    op.drop_table("task_executions")
    op.drop_table("stream_events")
    op.drop_table("runtime_settings")
    op.drop_index(op.f("ix_metric_samples_created_at"), table_name="metric_samples")
    op.drop_table("metric_samples")
    op.drop_index(op.f("ix_experiments_created_at"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_index(op.f("ix_deployments_scope_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_created_at"), table_name="deployments")
    op.drop_table("deployments")
    # ### end Alembic commands ###
