"""identity_and_applications

Revision ID: 0002
Revises: 0001
"""

from datetime import datetime, timezone

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_audit",
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target", sa.String(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_access_audit_created_at"), "access_audit", ["created_at"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_accounts_created_at"), "accounts", ["created_at"], unique=False)
    op.create_table(
        "applications",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_applications_created_at"), "applications", ["created_at"], unique=False)
    op.create_table(
        "login_buckets",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("window", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "application_members",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("application_id", "account_id"),
    )
    op.create_table(
        "connector_credentials",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_connector_credentials_application_id"),
        "connector_credentials",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connector_credentials_created_at"), "connector_credentials", ["created_at"], unique=False
    )
    op.create_table(
        "login_sessions",
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_login_sessions_account_id"), "login_sessions", ["account_id"], unique=False)
    op.create_index(op.f("ix_login_sessions_created_at"), "login_sessions", ["created_at"], unique=False)
    op.create_index(op.f("ix_login_sessions_expires_at"), "login_sessions", ["expires_at"], unique=False)
    op.bulk_insert(
        sa.table(
            "applications",
            sa.column("id", sa.String),
            sa.column("name", sa.String),
            sa.column("kind", sa.String),
            sa.column("active", sa.Boolean),
            sa.column("created_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "id": "00000000-0000-0000-0000-000000000001",
                "name": "Local workload",
                "kind": "local",
                "active": True,
                "created_at": datetime.now(timezone.utc),
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_sessions_expires_at"), table_name="login_sessions")
    op.drop_index(op.f("ix_login_sessions_created_at"), table_name="login_sessions")
    op.drop_index(op.f("ix_login_sessions_account_id"), table_name="login_sessions")
    op.drop_table("login_sessions")
    op.drop_index(op.f("ix_connector_credentials_created_at"), table_name="connector_credentials")
    op.drop_index(op.f("ix_connector_credentials_application_id"), table_name="connector_credentials")
    op.drop_table("connector_credentials")
    op.drop_table("application_members")
    op.drop_table("login_buckets")
    op.drop_index(op.f("ix_applications_created_at"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_accounts_created_at"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_access_audit_created_at"), table_name="access_audit")
    op.drop_table("access_audit")
    # ### end Alembic commands ###
